---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /Users/niteeshreddy/miniforge3/bin/python
  tasks:
    - name: Install Docker Python module
      pip:
            name: docker
            state: present
    - name: Pull image
      docker_image:
        name: niteesh5547/scientificcalculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator niteesh5547/scientificcalculator