---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      shell: docker pull niteesh5547/scientificcalculator:latest
    - name: Running container
      shell: docker run -it -d --name scientific niteesh5547/scientificcalculator