---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /Users/niteeshreddy/miniforge3/bin/python
  tasks:
    - name: Copy SSH public key to the remote host
      authorized_key:
        user: niteeshreddy
        key: "{{ lookup('file', '/path/to/your/public/key/id_rsa.pub') }}"
        state: present
        exclusive: yes

    - name: Pull image
      docker_image:
        name: niteesh5547/scientificcalculator:latest
        source: pull

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name calculator niteesh5547/scientificcalculator
